import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type MinimalAppRequest = {
  name: string;
  template?: "nextjs-app";
};

type NextJsTemplateContract = {
  name: string;
  framework: string;
  router: string;
  ui: string;
  components: string;
  testing: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../..");
const artifactsRoot = path.join(__dirname, "artifacts");
const nextjsTemplatePath = path.join(
  repoRoot,
  "templates",
  "nextjs-app",
  "template.json",
);

function sanitizeAppName(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "nextjs-app"
  );
}

async function readRequest(): Promise<MinimalAppRequest> {
  const raw = process.argv[2];

  if (!raw) {
    return { name: "my-nextjs-app", template: "nextjs-app" };
  }

  const parsed = JSON.parse(raw) as Partial<MinimalAppRequest>;

  return {
    name: parsed.name?.trim() || "my-nextjs-app",
    template: "nextjs-app",
  };
}

async function loadTemplate(): Promise<NextJsTemplateContract> {
  const raw = await fs.readFile(nextjsTemplatePath, "utf8");
  return JSON.parse(raw) as NextJsTemplateContract;
}

async function writeFile(targetPath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, content, "utf8");
}

async function generateNextJsApp(
  outputDir: string,
  request: MinimalAppRequest,
  template: NextJsTemplateContract,
): Promise<void> {
  const packageJson = {
    name: sanitizeAppName(request.name),
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      test: "vitest",
    },
    dependencies: {
      next: "^15.0.0",
      react: "^18.3.1",
      "react-dom": "^18.3.1",
    },
    devDependencies: {
      typescript: "^5.0.0",
      "@types/node": "^22.0.0",
      "@types/react": "^18.3.0",
      "@types/react-dom": "^18.3.0",
      tailwindcss: "^4.0.0",
      vitest: "^2.0.0",
    },
  };

  await writeFile(
    path.join(outputDir, "package.json"),
    `${JSON.stringify(packageJson, null, 2)}\n`,
  );

  await writeFile(
    path.join(outputDir, "tsconfig.json"),
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
        },
        include: [
          "next-env.d.ts",
          "**/*.ts",
          "**/*.tsx",
          ".next/types/**/*.ts",
        ],
        exclude: ["node_modules"],
      },
      null,
      2,
    )}\n`,
  );

  await writeFile(
    path.join(outputDir, "next-env.d.ts"),
    `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is auto-generated by Next.js.\n`,
  );

  await writeFile(
    path.join(outputDir, "next.config.mjs"),
    `const nextConfig = {};\n\nexport default nextConfig;\n`,
  );

  await writeFile(
    path.join(outputDir, "app", "layout.tsx"),
    `import './globals.css';\nimport type { Metadata } from 'next';\n\nexport const metadata: Metadata = {\n  title: '${request.name}',\n  description: 'Generated by the minimal build runner',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
  );

  await writeFile(
    path.join(outputDir, "app", "page.tsx"),
    `export default function HomePage() {\n  return (\n    <main style={{ padding: '2rem', fontFamily: 'Arial, sans-serif' }}>\n      <h1>${request.name}</h1>\n      <p>Framework: ${template.framework}</p>\n      <p>Router: ${template.router}</p>\n      <p>UI: ${template.ui}</p>\n      <p>Components: ${template.components}</p>\n      <p>Testing: ${template.testing}</p>\n    </main>\n  );\n}\n`,
  );

  await writeFile(
    path.join(outputDir, "app", "globals.css"),
    `@import "tailwindcss";\n\nhtml, body {\n  margin: 0;\n  padding: 0;\n}\n\nbody {\n  min-height: 100vh;\n}\n`,
  );

  await writeFile(
    path.join(outputDir, "README.md"),
    `# ${request.name}\n\nGenerated by services/build-runner/runner.ts using the nextjs-app template contract.\n`,
  );
}

export async function run(): Promise<{
  outputDir: string;
  template: NextJsTemplateContract;
}> {
  const request = await readRequest();
  const template = await loadTemplate();

  if (request.template && request.template !== template.name) {
    throw new Error(`Unsupported template: ${request.template}`);
  }

  if (template.framework !== "nextjs") {
    throw new Error(`Unsupported framework in template: ${template.framework}`);
  }

  const appDirName = sanitizeAppName(request.name);
  const outputDir = path.join(artifactsRoot, appDirName);

  await fs.rm(outputDir, { recursive: true, force: true });
  await fs.mkdir(outputDir, { recursive: true });
  await generateNextJsApp(outputDir, request, template);

  return { outputDir, template };
}

run()
  .then(({ outputDir, template }) => {
    console.log(
      JSON.stringify(
        {
          ok: true,
          outputDir,
          template: template.name,
        },
        null,
        2,
      ),
    );
  })
  .catch((error: unknown) => {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error(message);
    process.exitCode = 1;
  });
